controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['front_left_wheel_joint', 'back_left_wheel_joint']
    right_wheel_names: ['front_right_wheel_joint', 'back_right_wheel_joint']
    wheel_separation: 0.788
    wheel_radius: 0.11736

    use_stamped_vel: false

    wheels_per_side: 2
    # wheel_separation_multiplier: x
    # left_wheel_radius_multiplier: x
    # right_wheel_radius_multiplier: x

    # odom_frame_id: x
    pose_covariance_diagonal: [0.002, 0.002, 0.0, 0.0, 0.0, 0.02]
    twist_covariance_diagonal: [0.002, 0.0, 0.0, 0.0, 0.0, 0.02]

    open_loop: false
    enable_odom_tf: false

    cmd_vel_timeout: 0.5
    # publish_limited_velocity: x
    # velocity_rolling_window_size: x
    

    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    # linear.x.has_jerk_limits: false
    linear.x.max_velocity: 2.5
    linear.x.min_velocity: -2.5
    linear.x.max_acceleration: 5.0
    linear.x.min_acceleration: -5.0
    # linear.x.max_jerk: NAN
    # linear.x.min_jerk: NAN

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    # angular.z.has_jerk_limits: false
    angular.z.max_velocity: 2.5
    angular.z.min_velocity: -2.5
    angular.z.max_acceleration: 5.0
    angular.z.min_acceleration: -5.0
    # angular.z.max_jerk: NAN
    # angular.z.min_jerk: NAN




# joint_broad:
#   ros__parameters: