services:
        imu:
                image: cengaver/imu:latest
                privileged: true
                entrypoint: ["/autostart.sh", "terminal"]
                network_mode: host
                ipc: host
                volumes:
                        - ./../config:/configs
        lidar:
                image: cengaver/lidar:latest
                privileged: true
                entrypoint: ["/autostart.sh", "terminal"]
                network_mode: host
                ipc: host
                volumes:
                        - ./../config:/configs
        controls:
                image: cengaver/controls:latest
                privileged: true
                entrypoint: ["/autostart.sh", "terminal"]
                network_mode: host
                ipc: host
                volumes:
                        - ./../config:/configs
        #cameras:
        #        image: cengaver/controls:latest
        #        privileged: true
        #        entrypoint: [ "/autostart.sh" ]
        #        network_mode: host
        #        ipc: host
        #        volumes:
        #                - ./../config:/config