services:
        #imu:
        #        image: cengaver/imu:latest
        #        privileged: true
        #        entrypoint: ["/autostart.sh", "terminal"]
        #        network_mode: host
        #        ipc: host
        #        volumes:
        #                - ./../config:/configs
        #lidar:
        #        image: cengaver/lidar:latest
        #        privileged: true
        #        entrypoint: ["/autostart.sh", "terminal"]
        #        network_mode: host
        #        ipc: host
        #        volumes:
        #                - ./../config:/configs
        foxglove_bridge:
                image: cengaver/foxglove_bridge:latest
                privileged: true
                entrypoint: ["/autostart.sh", "terminal"]
                network_mode: host
                ipc: host
        foxglove_controller:
                image: cengaver/foxglove_controller:latest
                privileged: true
                entrypoint: ["/autostart.sh", "terminal"]
                network_mode: host
                ipc: host
        #cameras:
        #        image: cengaver/controls:latest
        #        privileged: true
        #        entrypoint: [ "/autostart.sh" ]
        #        network_mode: host
        #        ipc: host
        #        volumes:
        #                - ./../config:/config
