services:
        imu:
                image: cengaver/imu:latest
                privileged: true
                entrypoint: ["/autostart.sh"]
                network_mode: host
                ipc: host
        lidar:
                image: cengaver/lidar:latest
                privileged: true
                entrypoint: ["/autostart.sh"]
                network_mode: host
                ipc: host
        rover-description:
                image: cengaver/rover-description:latest
                privileged: true
                entrypoint: ["/autostart.sh"]
                network_mode: host
                ipc: host
        microros:
                image: microros/micro-ros-agent:humble
                privileged: true
                network_mode: host
                ipc: host
                command: serial --dev /dev/ttyAMC0
