#!/bin/bash

options=("lidar" "lidar-simulation" "imu" "descriptor" "micro-ros-agent")

if [ -z "$1" ]; then
	echo "Usage: $0 <name>"
 	echo "Available options:"
	for i in "${options[@]}"; do
		echo "$i"
	done
	exit 1
fi
if [ "$1" == "lidar-simulation" ]; then
	docker run --privileged --net=host --ipc=host -it cengaver/lidar:latest bash /autostart.sh use_sim_time:=true
	wait ; exit
elif [ "$1" == "micro-ros-agent" ]; then
	docker run -it --net=host microros/micro-ros-agent:humble udp4 -p 9999
	wait ; exit
fi
docker run \
	--privileged \
       	--ipc=host \
	--net=host \
	-it cengaver/"$1":latest \
       	/autostart.sh
