#!/bin/bash

for dockerfile in ./*/Dockerfile; do
    dir=$(dirname "$dockerfile")
    tag=$(basename "$dir")

    printf '\e[1;34m%-6s\e[m\n' "Building denavdot/$tag"
    
    docker build -f "$dockerfile" -t "denavdot/$tag" "$dir"
    
    if [ $? -ne 0 ]; then
        printf '\e[1;31m%-6s\e[m\n' "!!!Failed to build image for $tag!!!"
        exit 1
    fi
done

echo "All Dockerfiles have been successfully built!"
